package:
  name: meshmonk
  version: "0.0.5"

source:
  git_rev: v0.0.4
  git_url: https://github.com/TheWebMonks/meshmonk.git

requirements:
  build:
    - python ==2.7.8
    - setuptools
    - numpy ==1.11.0
    - scipy ==0.18.1
  run:
    - python ==2.7.8
    - numpy ==1.11.0
    - scipy ==0.18.1

about:
  home: https://github.com/TheWebMonks/meshmonk
  license: MIT
  license_file: LICENSE
