package:
  name: meshmonk
  version: "0.0.2"

source:
  git_rev: v0.0.2
  git_url: https://bitbucket.org/webmonks/kuleuven-algorithms.git

requirements:
  build:
    - python ==2.7.8
    - setuptools
    - numpy ==1.11.0
    - scipy ==0.18.1
  run:
    - python ==2.7.8
    - numpy ==1.11.0
    - scipy ==0.18.1

about:
  home: https://bitbucket.org/webmonks/kuleuven-algorithms
  license: MIT
  license_file: LICENSE.txt
